### ISSUE TITLE
urllib3 dependency

### ISSUE THREAD

**Issue by brandonw** [GoogleCloudPlatform/google-resumable-media-python#43]
Commit b6c62d80ad8415626fade6caf4282939862996bd introduced a dependency on the urllib3 library without a corresponding addition in the setup.py

As of now, if the latest version of google-resumable-media-python is used in a project that does not otherwise require urllib3, then the following error will be encountered:

`ImportError: No module named urllib3.response`

**Comment by dhermes** [comment]
@brandonw It's included transitively by the [`requests >= 2.18.0`][1] "extra" and the `google.resumable_media.requests` package can't be used without the extra.

How are you installing `google-resumable-media`? If you've done it via `google-cloud-storage`, you will have gotten the extra.

Also, see #42 for a previous discussion of this. I am going to close since this is "working as intended" but am happy to continue the discussion.

[1]: https://github.com/GoogleCloudPlatform/google-resumable-media-python/blob/8700f14e7c72501df557aee95c8a2426dc8c4f4c/setup.py#L31

**Comment by brandonw** [comment]
@dhermes Ah, that makes sense. I am installing it via `google-cloud`, but we have the `requests` library pinned to an earlier version, hence not pulling in `urllib3` automatically.

Pipfile would be useful here :-) Thanks for the insight.
